spring.application.name=f1-standings
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=embedded
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.session.jdbc.initialize-schema=always
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

