insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (1, 'Redbull', 'Honda', 'Laurent Mekies', 451);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (2, 'Ferrari', 'Ferrari', 'Frederic Vasseur', 398);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (3, 'Mclaren', 'Mercedes', 'Zack Brown', 833);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (4, 'Mercedes', 'Mercedes', 'Toto Wolff', 469);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (5, 'Williams', 'Mercedes', 'James Vowles', 137);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (6, 'RB', 'Honda', 'Alan Permane', 92);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (7, 'Aston Martin', 'Mercedes', 'Andy Cowell', 89);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (8, 'Haas', 'Ferrari', 'Ayao Komats', 79);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (9, 'Sauber', 'Ferrari', 'Jonathan Wheatley', 70);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (10, 'Alpine', 'Renault', 'Flavio Briatore', 22);

insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (1, 'Lando Norris', 'Mclaren', 423, 7, 18);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (2, 'Max Verstappen', 'Redbull', 421, 8, 15);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (3, 'Oscar Piastri', 'Mclaren', 410, 7, 16);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (4, 'George Russell', 'Mercedes', 319, 2, 9);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (5, 'Charles Leclerc', 'Ferrari', 242, 0, 7);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (6, 'Lewis Hamilton', 'Ferrari', 156, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (7, 'Kimi Antonelli', 'Mercedes', 150, 0, 3);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (8, 'Alexander Albon', 'Williams', 73, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (9, 'Carlos Sainz', 'Williams', 64, 0, 2);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (10, 'Fernando Alonso', 'Aston Martin', 56, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (11, 'Nico Hulkenberg', 'Sauber', 51, 0, 1);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (12, 'Isack Hadjar', 'RB', 51, 0, 1);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (13, 'Oliver Bearman', 'Haas', 41, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (14, 'Liam Lawson', 'RB', 38, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (15, 'Esteban Ocon', 'Haas', 38, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (16, 'Lance Stroll', 'Aston Martin', 33, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (17, 'Yuki Tsunoda', 'Redbull', 33, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (18, 'Pierre Gasly', 'Alpine', 22, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (19, 'Gabriel Bortoleto', 'Sauber', 19, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (20, 'Fernando Colapinto', 'Alpine', 0, 0, 0);


INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (1,  '2025-03-14', 'Australia',      0, 58);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (2,  '2025-03-21', 'China',          1, 56);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (3,  '2025-04-04', 'Japan',          0, 53);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (4,  '2025-04-11', 'Bahrain',        0, 57);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (5,  '2025-04-18', 'Saudi Arabia',   0, 50);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (6,  '2025-05-02', 'USA',            1, 57);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (7,  '2025-05-16', 'Italy',          0, 63);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (8,  '2025-05-23', 'Monaco',         0, 78);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (9,  '2025-05-30', 'Spain',          0, 66);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (10, '2025-06-13', 'Canada',         0, 70);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (11, '2025-06-27', 'Austria',        0, 71);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (12, '2025-07-04', 'United Kingdom', 0, 52);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (13, '2025-07-25', 'Belgium',        1, 44);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (14, '2025-08-01', 'Hungary',        0, 70);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (15, '2025-08-29', 'Netherlands',    0, 72);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (16, '2025-09-05', 'Italy',          0, 53);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (17, '2025-09-19', 'Azerbaijan',     0, 51);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (18, '2025-10-03', 'Singapore',      0, 61);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (19, '2025-10-17', 'USA',            1, 56);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (20, '2025-10-24', 'Mexico',         0, 71);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (21, '2025-11-07', 'Brazil',         1, 71);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (22, '2025-11-20', 'USA',            0, 50);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (23, '2025-11-28', 'Qatar',          1, 57);
INSERT INTO Curse(id, data_cursei, tara, is_sprint, nr_laps) VALUES (24, '2025-12-05', 'UAE',            0, 58);

INSERT INTO users(username, password, role)VALUES ('user','$2a$12$2di3sHp6FpOtqQPoJROs9ue3yiorSVU5oC3XHKyEhics5Y1NFSlsS','USER');
INSERT INTO users(username, password, role)VALUES ('Vlad','$2a$12$Zl83w6VWkdhecFj8y6AlLuW1i9YKPRQOCeMIlPz.5V8QraoAZYpI6','USER');