insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (1, 'Redbull', 'Honda', 'Laurent Mekies', 451);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (2, 'Ferrari', 'Ferrari', 'Frederic Vasseur', 398);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (3, 'Mclaren', 'Mercedes', 'Zack Brown', 833);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (4, 'Mercedes', 'Mercedes', 'Toto Wolff', 469);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (5, 'Williams', 'Mercedes', 'James Vowles', 137);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (6, 'RB', 'Honda', 'Alan Permane', 92);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (7, 'Aston Martin', 'Mercedes', 'Andy Cowell', 89);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (8, 'Haas', 'Ferrari', 'Ayao Komats', 79);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (9, 'Sauber', 'Ferrari', 'Jonathan Wheatley', 70);
insert into Echipe(id, nume, powerunit, Team_principal, nr_puncte) values (10, 'Alpine', 'Renault', 'Flavio Briatore', 22);

insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (1, 'Lando Norris', 'Mclaren', 423, 7, 18);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (2, 'Max Verstappen', 'Redbull', 421, 8, 15);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (3, 'Oscar Piastri', 'Mclaren', 410, 7, 16);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (4, 'George Russell', 'Mercedes', 319, 2, 9);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (5, 'Charles Leclerc', 'Ferrari', 242, 0, 7);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (6, 'Lewis Hamilton', 'Ferrari', 156, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (7, 'Kimi Antonelli', 'Mercedes', 150, 0, 3);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (8, 'Alexander Albon', 'Williams', 73, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (9, 'Carlos Sainz', 'Williams', 64, 0, 2);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (10, 'Fernando Alonso', 'Aston Martin', 56, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (11, 'Nico Hulkenberg', 'Sauber', 51, 0, 1);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (12, 'Isack Hadjar', 'RB', 51, 0, 1);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (13, 'Oliver Bearman', 'Haas', 41, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (14, 'Liam Lawson', 'RB', 38, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (15, 'Esteban Ocon', 'Haas', 38, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (16, 'Lance Stroll', 'Aston Martin', 33, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (17, 'Yuki Tsunoda', 'Redbull', 33, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (18, 'Pierre Gasly', 'Alpine', 22, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (19, 'Gabriel Bortoleto', 'Sauber', 19, 0, 0);
insert into Drivers(id, nume, echipa, nr_puncte, nr_victorii, nr_podiumuri) values (20, 'Fernando Colapinto', 'Alpine', 0, 0, 0);